// RPGPlayer/Core/Engine/PluginManager.swift
//
// Reads, toggles, and writes js/plugins.js for RPG Maker MV / MZ games.
//
// Format of plugins.js (both MV and MZ):
//   //=============================================================================
//   // Plugins file.
//   //=============================================================================
//   var $plugins = [
//     {"name":"PluginName","status":true,"description":"...", "parameters":{"key":"val"}},
//     ...
//   ];
//
// We use JavaScriptCore to safely evaluate the file and extract $plugins,
// avoiding fragile regex on potentially complex nested parameter objects.
// License: JavaScriptCore is part of WebKit / iOS SDK — no third-party dependency.

import Foundation
import JavaScriptCore

// MARK: - RPGPlugin

/// Represents one entry in RPG Maker MV/MZ js/plugins.js
struct RPGPlugin: Identifiable, Equatable {
    let id: UUID
    var name: String
    var status: Bool
    var description: String
    /// Raw parameters dict — values are strings per RPG Maker convention.
    /// We preserve whatever was in the file so we don't corrupt user settings.
    var parameters: [String: Any]

    init(name: String, status: Bool, description: String, parameters: [String: Any]) {
        self.id          = UUID()
        self.name        = name
        self.status      = status
        self.description = description
        self.parameters  = parameters
    }

    static func == (lhs: RPGPlugin, rhs: RPGPlugin) -> Bool {
        lhs.id == rhs.id
    }
}

// MARK: - PluginManager

enum PluginManager {

    // MARK: - Load

    /// Loads plugins from `<gameRoot>/js/plugins.js`.
    /// Returns nil if the file is absent (game has no plugin list).
    /// Returns [] if the file exists but $plugins is empty.
    static func loadPlugins(from gameRoot: URL) -> [RPGPlugin]? {
        let pluginsURL = gameRoot
            .appendingPathComponent("js")
            .appendingPathComponent("plugins.js")

        guard FileManager.default.fileExists(atPath: pluginsURL.path) else {
            print("[PluginManager] plugins.js not found at \(pluginsURL.path)")
            return nil
        }

        guard let source = try? String(contentsOf: pluginsURL, encoding: .utf8) else {
            print("[PluginManager] ❌ Cannot read plugins.js")
            return nil
        }

        return parsePluginsJS(source)
    }

    // MARK: - Parse (via JavaScriptCore)

    private static func parsePluginsJS(_ source: String) -> [RPGPlugin]? {
        // a3 fix: JSContext() can return nil on devices with JS disabled.
        // Guard instead of force-unwrapping to avoid a crash.
        guard let ctx = JSContext() else {
            print("[PluginManager] ❌ JSContext() returned nil — cannot parse plugins.js")
            return nil
        }
        // Silence JS exceptions — catch them ourselves
        ctx.exceptionHandler = { _, exception in
            print("[PluginManager] JS parse error: \(exception?.toString() ?? "unknown")")
        }

        // Evaluate the file. This sets `$plugins` in the JS context.
        ctx.evaluateScript(source)

        guard let pluginsValue = ctx.objectForKeyedSubscript("$plugins"),
              !pluginsValue.isNull, !pluginsValue.isUndefined,
              let pluginsArray = pluginsValue.toArray() else {
            print("[PluginManager] ❌ $plugins is null/undefined after evaluation")
            return nil
        }

        var result: [RPGPlugin] = []
        for item in pluginsArray {
            guard let dict = item as? [String: Any] else { continue }

            let name        = dict["name"]        as? String ?? ""
            let status      = dict["status"]      as? Bool   ?? true
            let description = dict["description"] as? String ?? ""
            let parameters  = dict["parameters"]  as? [String: Any] ?? [:]

            guard !name.isEmpty else { continue }

            result.append(RPGPlugin(
                name:        name,
                status:      status,
                description: description,
                parameters:  parameters
            ))
        }

        print("[PluginManager] ✅ Parsed \(result.count) plugins")
        return result
    }

    // MARK: - Save

    /// Writes plugins back to `<gameRoot>/js/plugins.js`.
    /// Preserves the standard RPG Maker file header comment and format.
    ///
    /// Output format:
    ///   // Generated by RPG Player — edit with caution.
    ///   var $plugins =\n[\n{"name":...},\n...];
    ///
    /// - Throws: any FileManager / encoding error
    static func savePlugins(_ plugins: [RPGPlugin], to gameRoot: URL) throws {
        let pluginsURL = gameRoot
            .appendingPathComponent("js")
            .appendingPathComponent("plugins.js")

        let body = try buildPluginsJS(plugins)
        try body.write(to: pluginsURL, atomically: true, encoding: .utf8)
        print("[PluginManager] ✅ Saved \(plugins.count) plugins to \(pluginsURL.lastPathComponent)")
    }

    // MARK: - Serialise

    private static func buildPluginsJS(_ plugins: [RPGPlugin]) throws -> String {
        var lines: [String] = []
        lines.append("// Generated by RPG Player — original content preserved.")
        lines.append("// Modifying plugin status here may affect game behaviour.")
        lines.append("var $plugins =")
        lines.append("[")

        for (index, plugin) in plugins.enumerated() {
            let comma = index < plugins.count - 1 ? "," : ""
            let statusStr = plugin.status ? "true" : "false"
            let escapedName = jsonEscapeString(plugin.name)
            let escapedDesc = jsonEscapeString(plugin.description)
            let paramsJSON  = try serializeParameters(plugin.parameters)
            lines.append("{\"name\":\"\(escapedName)\",\"status\":\(statusStr),\"description\":\"\(escapedDesc)\",\"parameters\":\(paramsJSON)}\(comma)")
        }

        lines.append("];")
        return lines.joined(separator: "\n")
    }

    /// Serialise a parameter dict back to JSON.
    /// All leaf values in RPG Maker parameters are strings, so this is
    /// straightforward — but we use JSONSerialization for correctness.
    private static func serializeParameters(_ params: [String: Any]) throws -> String {
        // Convert any non-Foundation-compatible values to string for safety
        var safe: [String: Any] = [:]
        for (k, v) in params {
            switch v {
            case let s as String:   safe[k] = s
            case let n as NSNumber: safe[k] = n.stringValue
            default:                safe[k] = "\(v)"
            }
        }
        let data = try JSONSerialization.data(withJSONObject: safe, options: [.sortedKeys])
        return String(data: data, encoding: .utf8) ?? "{}"
    }

    /// Minimal JSON string escaping for name/description fields.
    private static func jsonEscapeString(_ s: String) -> String {
        s
            .replacingOccurrences(of: "\\",  with: "\\\\")
            .replacingOccurrences(of: "\"",  with: "\\\"")
            .replacingOccurrences(of: "\n",  with: "\\n")
            .replacingOccurrences(of: "\r",  with: "\\r")
            .replacingOccurrences(of: "\t",  with: "\\t")
    }
}
